import { createClient } from "@supabase/supabase-js";
process.loadEnvFile("/Users/ryanmancuso/Code/matchday-cockpit/.env.local");
const svc = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth:{persistSession:false} });
const local=(s)=>new Date(String(s).replace(/([+-]\d\d:\d\d|Z)$/,""));
const links=(await svc.from("fin_venue_fields").select("fin_venue_id,mdapi_field_id")).data??[];
const scFields=links.filter(x=>x.fin_venue_id===11||x.fin_venue_id===53).map(x=>x.mdapi_field_id);
const rows=(await svc.from("mdapi_matches").select("field_id,field_title,start_date,is_cancelled,max_player_count,deleted_at").in("field_id",scFields)).data??[];
const aug=rows.filter(r=>!r.deleted_at&&r.start_date&&(()=>{const d=local(r.start_date);return d.getFullYear()===2026&&d.getMonth()===7;})());
const big=aug.filter(r=>(r.max_player_count??0)>22);
const small=aug.filter(r=>(r.max_player_count??0)<=22 && (r.max_player_count??0)>0);
const ev=aug.filter(r=>!r.max_player_count);
console.log(`Soccer Central fields ${scFields.join(", ")} · Aug 2026 matches: ${aug.length}`);
console.log(`   max_player_count > 22  (routed to the $120 leg): ${big.length}  → ${big.length}×$120 = $${big.length*120}`);
console.log(`   max_player_count ≤ 22  (the $60/$80 primary leg): ${small.length}`);
console.log(`   max_player_count null/0 (special event, no cost): ${ev.length}`);
console.log(`\n   primary keyed month value $5,600 + secondary ${big.length}×$120 = $${5600+big.length*120}`);
console.log(`   page renders $6,080 → ${5600+big.length*120===6080?"MATCHES ✓":"does not match"}`);
